CUDA_VISIBLE_DEVICES=8 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-125m &
CUDA_VISIBLE_DEVICES=8 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-350m &
CUDA_VISIBLE_DEVICES=8 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-1.3b &
CUDA_VISIBLE_DEVICES=8 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-2.7b &
CUDA_VISIBLE_DEVICES=9 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --max_output_length 128 --model T0_3B &
CUDA_VISIBLE_DEVICES=9 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-6.7b &
CUDA_VISIBLE_DEVICES=14,15 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --max_output_length 128 --model T0 &
CUDA_VISIBLE_DEVICES=14,15 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-13b & 
CUDA_VISIBLE_DEVICES=8,9 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-30b
CUDA_VISIBLE_DEVICES=12,13,14,15 python score.py --dataset ai2_arc --dataset_config ARC-Easy --promptsource --sample 300 --prompt_name "q&a" --model opt-66b