CUDA_VISIBLE_DEVICES=0 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-125m
CUDA_VISIBLE_DEVICES=0 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-350m
CUDA_VISIBLE_DEVICES=8 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-1.3b
CUDA_VISIBLE_DEVICES=9 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-2.7b
CUDA_VISIBLE_DEVICES=4 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --max_output_length 128 --model T0_3B
CUDA_VISIBLE_DEVICES=9 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-6.7b
CUDA_VISIBLE_DEVICES=14,15 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-13b
CUDA_VISIBLE_DEVICES=0,1 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --max_output_length 128 --model T0
CUDA_VISIBLE_DEVICES=13,14,15 python score.py --dataset hellaswag --promptsource --sample 300 --prompt_name "Open-ended completion negation" --model opt-30b
