CUDA_VISIBLE_DEVICES=2 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-125m
CUDA_VISIBLE_DEVICES=2 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-350m
CUDA_VISIBLE_DEVICES=2 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-1.3b
CUDA_VISIBLE_DEVICES=3 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-2.7b
CUDA_VISIBLE_DEVICES=3 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --max_output_length 128 --model T0_3B
CUDA_VISIBLE_DEVICES=11 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-6.7b
CUDA_VISIBLE_DEVICES=4,5 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-13b
CUDA_VISIBLE_DEVICES=6,7 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --max_output_length 128 --model T0
CUDA_VISIBLE_DEVICES=8,9,10 python score.py --dataset story_cloze --dataset_config 2016 --promptsource --sample 300 --prompt_name "Generate Ending" --model opt-30b
